<a href="https://colab.research.google.com/github/dayanamichellgomezmartinez-ux/Notebooks_Agro_2026_1/blob/main/Taller_Metodos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAYANA GOMEZ MARTINEZ**

**EJERCICIO 1**

In [2]:
import numpy as np
from tabulate import tabulate

def jacobi_matricial_LDU(A, b, x_ini, imax=100, tol=1e-6):
    # Descomposición de la matriz A = L + D + U
    D = np.diag(np.diag(A))
    L = np.tril(A, -1)
    U = np.triu(A, 1)

    D_inv = np.linalg.inv(D)

    # Cálculo de la matriz TJ y el vector c
    TJ = -np.dot(D_inv, (L + U))
    c = np.dot(D_inv, b)

    print("Descomposición de A")
    print("L (Triangular inferior estricta):\n", L)
    print("\nD (Diagonal):\n", D)
    print("\nU (Triangular superior estricta):\n", U)

    print("\nMatriz de Iteración (TJ)")
    print(TJ)
    print("\nVector Constante (c)")
    print(c)
    print("\n" + "="*50 + "\n")

    x = x_ini.astype(float).copy()
    k = 0
    resultados = []

    # Iteración 0
    resultados.append([0] + list(x) + ["-"])

    cumple = False
    while not cumple and k < imax:
        k += 1
        x_prev = x.copy()

        # Cálculo del nuevo vector x
        x = np.dot(TJ, x_prev) + c

        # Cálculo del error relativo con norma infinito
        norma_num = np.linalg.norm(x - x_prev, ord=np.inf)
        norma_den = np.linalg.norm(x, ord=np.inf)
        error_relativo = norma_num / norma_den

        resultados.append([k] + list(x) + [error_relativo])

        # Verificación de tolerancia
        cumple = error_relativo < tol

    # Imprimir la tabla
    encabezados = ["k"] + [f"T{i+1}" for i in range(len(x))] + ["Error Relativo"]
    print(tabulate(resultados, headers=encabezados, tablefmt="grid"))

    if k < imax:
        return x
    else:
        raise ValueError('El sistema no converge en el número máximo de iteraciones permitidas')

def main():
    # Matriz de coeficientes A (4x4)
    A = np.array([
        [ 2.5, -1.0,  0.0,  0.0],
        [-1.0,  2.5, -1.0,  0.0],
        [ 0.0, -1.0,  2.5, -1.0],
        [ 0.0,  0.0, -1.0,  2.5]
    ])

    # Vector b
    b = np.array([120.0, 0.0, 0.0, 20.0])

    # Vector inicial de ceros
    x_inicial = np.array([0.0, 0.0, 0.0, 0.0])

    # Ejecución con tolerancia de 1e-6
    solucion = jacobi_matricial_LDU(A, b, x_inicial, tol=1e-6)

    print("\nSolución Final")
    for i, val in enumerate(solucion):
        print(f"T{i+1} = {val:.4f} °C")

if __name__ == "__main__":
    main()

Descomposición de A
L (Triangular inferior estricta):
 [[ 0.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]]

D (Diagonal):
 [[2.5 0.  0.  0. ]
 [0.  2.5 0.  0. ]
 [0.  0.  2.5 0. ]
 [0.  0.  0.  2.5]]

U (Triangular superior estricta):
 [[ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]

Matriz de Iteración (TJ)
[[-0.   0.4 -0.  -0. ]
 [ 0.4 -0.   0.4 -0. ]
 [-0.   0.4 -0.   0.4]
 [-0.  -0.   0.4 -0. ]]

Vector Constante (c)
[48.  0.  0.  8.]


+-----+---------+---------+---------+---------+------------------------+
|   k |      T1 |      T2 |      T3 |      T4 | Error Relativo         |
+=====+=========+=========+=========+=========+========================+
|   0 |  0      |  0      |  0      |  0      | -                      |
+-----+---------+---------+---------+---------+------------------------+
|   1 | 48      |  0      |  0      |  8      | 1.0                    |
+-----+---------+---------+---------+---------+----------------

**EJERCICIO 2**

In [1]:
import numpy as np
from tabulate import tabulate

def jacobi_matricial_LDU(A, b, x_ini, imax=100, tol=1e-6):
    # Descomposición de la matriz A = L + D + U
    D = np.diag(np.diag(A))
    L = np.tril(A, -1)
    U = np.triu(A, 1)

    D_inv = np.linalg.inv(D)

    # Cálculo de la matriz TJ y el vector c
    TJ = -np.dot(D_inv, (L + U))
    c = np.dot(D_inv, b)

    print("Descomposición de A")
    print("L (Triangular inferior estricta):\n", L)
    print("\nD (Diagonal):\n", D)
    print("\nU (Triangular superior estricta):\n", U)

    print("\nMatriz de Iteración (TJ)")
    print(TJ)
    print("\nVector Constante (c)")
    print(c)
    print("\n" + "="*50 + "\n")

    x = x_ini.astype(float).copy()
    k = 0
    resultados = []

    # Iteración 0
    resultados.append([0] + list(x) + ["-"])

    cumple = False
    while not cumple and k < imax:
        k += 1
        x_prev = x.copy()

        # Cálculo del nuevo vector x
        x = np.dot(TJ, x_prev) + c

        # Cálculo del error relativo con norma infinito
        norma_num = np.linalg.norm(x - x_prev, ord=np.inf)
        norma_den = np.linalg.norm(x, ord=np.inf)
        error_relativo = norma_num / norma_den

        resultados.append([k] + list(x) + [error_relativo])

        # Verificación de tolerancia
        cumple = error_relativo < tol

    # Imprimir la tabla
    encabezados = ["k"] + [f"x{i+1}" for i in range(len(x))] + ["Error Relativo"]
    print(tabulate(resultados, headers=encabezados, tablefmt="grid"))

    if k < imax:
        return x
    else:
        raise ValueError('El sistema no converge en el número máximo de iteraciones permitidas')

def main():
    # Matriz de coeficientes A (9x9) para el Ejercicio 2
    A = np.array([
        [ 45.0, -10.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0],
        [-10.0,  50.0, -12.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0],
        [  0.0, -12.0,  55.0, -15.0,   0.0,   0.0,   0.0,   0.0,   0.0],
        [  0.0,   0.0, -15.0,  60.0, -10.0,   0.0,   0.0,   0.0,   0.0],
        [  0.0,   0.0,   0.0, -10.0,  48.0,  -8.0,   0.0,   0.0,   0.0],
        [  0.0,   0.0,   0.0,   0.0,  -8.0,  52.0, -11.0,   0.0,   0.0],
        [  0.0,   0.0,   0.0,   0.0,   0.0, -11.0,  58.0, -14.0,   0.0],
        [  0.0,   0.0,   0.0,   0.0,   0.0,   0.0, -14.0,  62.0,  -9.0],
        [  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,  -9.0,  40.0]
    ])

    # Vector b
    b = np.array([150.0, 80.0, 110.0, 95.0, 200.0, 120.0, 180.0, 75.0, 130.0])

    # Vector inicial de 9 ceros
    x_inicial = np.zeros(9)

    # Ejecución con tolerancia de 1e-6
    solucion = jacobi_matricial_LDU(A, b, x_inicial, tol=1e-6)

    print("\nSolución Final")
    for i, val in enumerate(solucion):
        print(f"x{i+1} = {val:.4f}")

if __name__ == "__main__":
    main()

Descomposición de A
L (Triangular inferior estricta):
 [[  0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. -12.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. -15.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -10.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -8.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -11.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -14.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  -9.   0.]]

D (Diagonal):
 [[45.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 50.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 55.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 60.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 48.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 52.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 58.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 62.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 40.]]

U (Triangular superior estricta):
 [[  0. -10.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. -12.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 